pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'JDK17'
    }

    stages {

        stage('Build') {
            steps {
                dir('Maven1') {
                    sh 'mvn clean package'
                }
            }
        }

    }

    post {
        success {
            echo 'Snake Game Build Successful!'
        }

        failure {
            echo 'Build Failed!'
        }
    }
}