pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                dir('Maven1') {
                    sh '/opt/homebrew/bin/mvn clean package'
                }
            }
        }

    }
}